### ISSUE TITLE
Can't install: ptxas fatal: Ptx assembly aborted due to errors

### ISSUE THREAD

**Issue by gazay** [t-vi/warp-ctc#7]
Hello! Thank you for your great work.

As I saw in other issue – there are success installations of this package for python 3.5, cuda 9.2 and pytorch 0.5.0

But I have problem when try to build package:

```
~/warp-ctc/pytorch_binding$ python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_deps
-- cuda found TRUE
CMake Warning at CMakeLists.txt:52 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Torch found Torch_DIR-NOTFOUND
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/saint/warp-ctc/pytorch_binding/build/lib
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o
ptxas /tmp/tmpxft_00000a80_00000000-12_ctc_entrypoint.compute_30.ptx, line 1931; fatal   : Parsing error near 'u': syntax error
ptxas <macro util>, line 9; error   : Illegal modifier '.sync' for instruction 'mov'
ptxas fatal   : Ptx assembly aborted due to errors
CMake Error at warpctc_generated_ctc_entrypoint.cu.o.cmake:266 (message):
  Error generating file
  /home/saint/warp-ctc/pytorch_binding/build/lib/CMakeFiles/warpctc.dir/src/./warpctc_generated_ctc_entrypoint.cu.o


CMakeFiles/warpctc.dir/build.make:403: recipe for target 'CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o' failed
make[2]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/warpctc.dir/all' failed
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    'clean': Clean,
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 73, in run
    build_warpctc_so()
  File "setup.py", line 41, in build_warpctc_so
    assert res.returncode == 0, "Error"
AssertionError: Error
```

Do have an idea why is this happening? Maybe I can provide some other information to help you understand the issue?
I'm using gcc 5.4, cudnn 7.1.4 for cuda 9.2 and python 3.5.2 in Ubuntu 16.04

**Comment by t-vi** [comment]
Hm I'm certainly using something very similar (master PyTorch, cuda 9.2, recent cudnn, gcc-5.5 from Debian). Does PyTorch build ok from source in your setup?

**Comment by gazay** [comment]
Yes, PyTorch master was built ok. There were breaking changes few days ago (https://github.com/pytorch/pytorch/commit/cffca2926b09970bd46a9fa49dda19f0a90d016d), I was able to build Sean's warp-ctc version only after building pytorch from previous commit. But as I can see in backtrace – here is the problem with some C++ code in bindings, but I'm not sure what exactly

**Comment by t-vi** [comment]
PTXAS means that the error is in warp-ctc, not the bindings.

If it doesn't work after setup.py clean build , could you try building the lib from the main dir as with the instructions from baidu, please?

**Comment by ayumiymk** [comment]
I have the same question as gazay. I also try building the lib from the main dir as with the instructions from baidu. but the same errors raise.

**Comment by t-vi** [comment]
Hi, 

I have finally reproduced it and the fix is simple enough. Apparently I had something cached that wasn't rebuilt during testing.
Thank you for your effort in reporting it!
I have pushed a fix.

Best regards

Thomas
