### ISSUE TITLE
Failed inf tests

### ISSUE THREAD

**Issue by carmocca** [t-vi/warp-ctc#8]
When I run the tests after installing, two of them fail.

```python3
$ python3 tests/test.py 
/home/carmocca/PyLaia/PyLaia-env/lib/python3.5/site-packages/torch-0.4.1-py3.5-linux-x86_64.egg/torch/autograd/gradcheck.py:179: UserWarning: At least one of the inputs that requires gradient is not of double precision floating point. This check will likely fail if all the inputs are not of double precision floating point. 
  'At least one of the inputs that requires gradient '
..FF.....
======================================================================
FAIL: test_inf_cpu (__main__.TestWarpCTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test.py", line 168, in test_inf_cpu
    self.inf_test(cuda=False)
  File "tests/test.py", line 124, in inf_test
    self.assertEqual(cost, float("inf"), msg="cost should be inf")
AssertionError: tensor(184.0796, grad_fn=<CTCFunctionBackward>) != inf : cost should be inf

======================================================================
FAIL: test_inf_gpu (__main__.TestWarpCTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test.py", line 171, in test_inf_gpu
    self.inf_test(cuda=True)
  File "tests/test.py", line 124, in inf_test
    self.assertEqual(cost, float("inf"), msg="cost should be inf")
AssertionError: tensor(267.9613, grad_fn=<CTCFunctionBackward>) != inf : cost should be inf

----------------------------------------------------------------------
Ran 9 tests in 7.938s

FAILED (failures=2)
```

In case it helps, here is my setup:
- PyTorch version: 0.4.1
- Is debug build: No
- CUDA used to build PyTorch: 9.0.176
- OS: Ubuntu 16.04.4 LTS
- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: version 3.5.1
- Python version: 3.5
- Is CUDA available: Yes
- CUDA runtime version: 9.0.176
- GPU models and configuration: GPU 0: GeForce GTX 1080
- Nvidia driver version: 390.67

As a side note, I believe the tests should check if CUDA is available since warp-ctc itself supports using the CPU.

Thank you.

**Comment by t-vi** [comment]
This is expected due to the minimal probs patch, but I will revert that.

**Comment by t-vi** [comment]
Now the tests should pass.
